#ifndef _FLASH_TOOL_ERROR_CODE_DEF_H
#define _FLASH_TOOL_ERROR_CODE_DEF_H
typedef enum {
    //<8000 is defined by brom.dll mtk_status.h
    FT_SUCCESS = 8000,
    FT_EXCEPTION = 8001,
    FT_USER_PRESS_STOP_BUTTON = 8002,
    //SCAN USB ERROR
    FT_FIND_USB_ERROR = 8100,
    FT_FIND_GADGET_USB_ERROR = 8101,
    //PLATFORM ERROR
    FT_DL_PLATFORM_ERROR = 8200,
    //BACKUP->FORMAT->DL->RESTORE ERROR
    FT_UPGRADE_FOLDER_OVERLAPPED = 8300,
    FT_UPGRADE_FOLDER_NOT_EXSIT = 8301,
    FT_UPGRADE_DIR_CREATE_FAIL = 8302,
    FT_UPGRADE_FILE_CORRUPTED = 8303,
    FT_UPGRADE_FILE_NOT_EXSIT = 8304,
    FT_UPGRADE_BACKUP_ROM_NOT_EXSIT = 8305,
    FT_OTP_FILE_NOT_WORD_ALIGN = 8306,
    FT_UPGRADE_LAYOUT_CHANGED = 8307,

    //Others
    FT_FIND_NVRAM_ERROR     = 8400,
    FT_INVALID_FORMAT_ADDR_ERROR,
    FT_FIND_PLATFORM_ERROR,
    FT_FIND_STORAGE_ERROR,
    FT_FIND_IMAGEMAP_ERROR,
    FT_INVALIDE_SESSION_KEY,
    FT_INVALID_MEM_INFO,
    FT_SAVE_FILE_ERROR,
    FT_LOAD_DA_ERROR,
    FT_GET_DA_INFO_ERROR,
    FT_LOAD_CERT_ERROR,
    FT_LOAD_AUTH_ERROR,
    FT_GET_RESTORE_ITEM_ERROR,
    FT_RESTORE_ERROR,
    FT_FILE_FOLDER_IS_NOT_EXIST,
    FT_FILE_IS_NOT_EXIST,
    FT_FLASHTOOL_ERROR_CHKSUM_FAIL,
    FT_FLASHTOOL_INVALIDE_SCATTER,
    FT_LOAD_TRANSLATION_FILE_FAIL,
    FT_RPMB_WRITTEN_BEFORE_DL
} FLASH_TOOL_RESULT;
#endif //_FLASH_TOOL_ERROR_CODE_DEF_H
