#ifndef STRING_H
#define STRING_H

#include <QString>

typedef enum
{
    LANGUAGE_ENGLISH    = 0,
    LANGUAGE_ZH_CHINESE,
    LANGUAGE_TW_CHINESE
}Language_Tag;

#define LANGUAGE_TAG                        main_window_->GetLanguageTag()
#define IDC_BUTTON_HELP                     1
#define IDC_BUTTON_SENDREPORT               2

enum
{
    IDS_STRING_ERROR_UPDATE            = 0,
    IDS_STRING_CRASHED,
    IDS_STRING_WARNING_LOADDA,
    IDS_STRING_WARNING_LOADSCATTER,
    IDS_STRING_ERROR_TIMEOUT,
    IDS_STRING_ERROR_UNKNOWN,

    IDS_STRING_OPEN_DA,
    IDS_STRING_BIN,
    IDS_STRING_OPEN_SCATTER,
    IDS_STRING_MAP_FILE,
    IDS_STRING_DOWNLOAD_OK,


    IDS_STRING_ERROR_CHIPNOTSUPPORT,
    IDS_STRING_ERROR_STORAGENOTSUPPORT,
    IDS_STRING_WARNING_ROMNOTSELECT,

    IDS_STRING_FORMAT,
    IDS_STRING_FORMAT_OK,

    IDS_STRING_HAS_UPDATE,
    IDS_STRING_TRACE_MODE,
    IDS_STRING_ADVANCE_MODE,
    IDS_STRING_MARKBBM,
    IDS_STRING_WARNING_EXIT,
    IDS_STRING_EXIT,
    IDS_STRING_WARNING_LOADPRELOADER,

    IDS_STRING_MEMORY_TEST,
    IDS_STRING_MEMORY_TEST_SELECT_NOTHING,
    IDS_STRING_MEMORY_TEST_OK,

    IDS_STRING_SAVE_AS,
    IDS_STRING_OPEN_OTP_FILE,

    IDS_STRING_NO_COMPORT_DETECT,
    IDS_STRING_FAILED_FIND_COMPORT,
    IDS_STRING_FAILED_REGISTER_USB,

    IDS_STRING_PARAMETER,
    IDS_STRING_WRITE_OTP_OK,
    IDS_STRING_READ_OTP_OK,

    IDS_STRING_READ_BACK,
    IDS_STRING_READ_BACK_OK,
    IDS_STRING_SAVE_FILE,
    IDS_STRING_WARNING_ADDRB,

    IDS_STRING_WRITE_MEMORY,
    IDS_STRING_WRITE_MEMORY_OK,

    IDS_STRING_DOWNLOAD,

    IDS_STRING_OK,
    IDS_STRING_CANCEL,
    IDS_STRING_YES,
    IDS_STRING_NO,

    IDS_STRING_OPEN_SECFILE,
    IDS_STRING_OPEN_AUTHFILE,
    IDS_STRING_AUTH_BIN,
    IDS_STRING_SEC_BIN,

    IDS_STRING_LOGFOLDER,
    IDS_STRING_WARNING_LOADCERT,
    IDS_STRING_CERT_OK,
    IDS_STRING_HELP,
    IDS_STRING_WELCOME,

    IDS_STRING_SHOW_WELCOME,
    IDS_STRING_HIDE_WELCOME,
    IDS_STRING_SCENE_LIKEMOTA,
    IDS_STRING_SCENE_FMTALLDL,
    IDS_STRING_SCENE_FIRMWAREUPGRADE,
    IDS_STRING_SCENE_DOWNLOADONLY,

    IDS_STRING_ERROR_ALIGN,

    IDS_STRING_ONEDAY,
    IDS_STRING_ONEWEEK,
    IDS_STRING_ONEMONTH,
    IDS_STRING_THREEMONTH,

    IDS_STRING_OTP_WRITE_SETTING,
    IDS_STRING_OTP_READ_SETTING,

    IDS_STRING_BROM_ADAPTER,
    IDS_STRING_OPEN_DOWNLOAD_DATA,
    IDS_STRING_ERROR_DATALENGTH,
    IDS_STRING_ERROR_NOMEMORY,
    IDS_STRING_WARNING_LOADDATA,
    IDS_STRING_BROMDL_OK,
    IDS_STRING_BROMJUMP_OK,
    IDS_STRING_WARNING_PMT_CHANGE,
    IDS_STRING_SCENE_WIPE_DATA,
    IDS_STRING_SECURITYMODE,
    IDS_STRING_SECURITY_WARNING,
    IDS_STRING_SECURITY_ERROR,
    IDS_STRING_NOTALLOWED_UNLOCK,
    IDS_STRING_ERROR_DECRYPT,

    IDS_STRING_SEND_REPORT,
    IDS_STRING_LAUNCH_ASSISTANT_ERROR,
    IDS_STRING_NULL_WRITE_LOCATION_OTP,
    IDS_STRING_NULL_READ_LOCATION_OTP,
    IDS_STRING_ERROR_SCATTER_NOT_FOUND,

    IDS_STRING_SCIDOWNLOAD,
    IDS_STRING_CLONEDOWNLOAD,
    IDS_STRING_WARNING_LOADSCI,
    IDS_STRING_WARNING_SELECTRBFOLDER,
    IDS_STRING_WARNING_RESTOREFOLDER_EMPTY,

    IDS_STRING_ROMFILE_WARNING,

    IDS_STRING_TOOL_NAME,                
    IDS_STRING_ABOUT_TOOL,               
    IDS_STRING_DA_INFO,                  
    IDS_STRING_COPY_RIGHT,               
    IDS_STRING_CUSTOM_RELEASE,           
    IDS_STRING_INTERNEL_RELEASE,         
    IDS_STRING_BUILD,                    
    IDS_STRING_BUILD_DATE,               
    IDS_STRING_UPDATE,                   
    IDS_STRING_CHECK_UPDATE,             
    IDS_STRING_NEW_DETECT,
    IDS_STRING_REMIND,
    IDS_STRING_INSTALL_UPDATE,
    IDS_STRING_ENCRY,
    IDS_STRING_PASSWORD,
    IDS_STRING_PWD_ERROR,

    IDS_STRING_DLRISK_REMINDER,
    IDS_STRING_CONTINUE,
    IDS_STRING_WARNING,

    IDS_STRING_DEVICE_TEST,
    IDS_STRING_DEVICE_TEST_OK
};


extern const QString test;
extern const QString exitInfo;

QString LoadQString(Language_Tag languageID, int strID);

#endif // STRING_H
